### ISSUE TITLE
大牛买Air780E模块还是开发版？

### ISSUE THREAD

**Issue by an429075824** [0wQ/air780e-forwarder#11]
尴尬,小白第一次接触这个 有点懵

**Comment by 0wQ** [comment]
买开发板😂


________________________________
From: an429075824 ***@***.***>
Sent: Thursday, March 16, 2023 12:33:47 AM
To: 0wQ/air780e-forwarder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [0wQ/air780e-forwarder] 大牛买Air780E模块还是开发版？ (Issue #11)


尴尬,小白第一次接触这个 有点懵

**Comment by an429075824** [comment]
收到 😂
