### ISSUE TITLE
如何进行基站定时定位

### ISSUE THREAD

**Issue by hdp521** [0wQ/air780e-forwarder#16]
开机运行一周了 一直没看到定位信息发过来

**Comment by 0wQ** [comment]
https://github.com/0wQ/air780e-forwarder/blob/616d33b1c4479f3cd0cef9f28cdacaac21c2eeee/script/config.lua#L54-L55

默认关闭了，可以改一下，单位毫秒

**Comment by hdp521** [comment]
感谢 有空修改一下

**Comment by hdp521** [comment]
把0修改为1000*60*60
还是没有定位发过来

**Comment by 0wQ** [comment]
发现问题了，合宙网页版基站定位接口报错了，明天换 [lbsLoc](https://wiki.luatos.com/api/libs/lbsLoc.html) 试试
