### ISSUE TITLE
大佬看看能不能加个ESP32C3核心板用WiFi啊

### ISSUE THREAD

**Issue by heyzg** [0wQ/air780e-forwarder#17]
大佬看看能不能加个ESP32C3核心板用WiFi啊
我有几张0月租的卡没流量，不好弄，大佬看看能不能加个WiFi板子
另外合宙出新的780ex板子了，支持电信了，大佬这个代码支持吗

**Comment by 0wQ** [comment]
可以用这个 https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html

我卡都是有流量的，可能以后会加吧 😂

780ex 应该也能刷，支持电信应该指的是支持电信上网，不是指的短信

**Comment by heyzg** [comment]
> 可以用这个 https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html
> 
> 我卡都是有流量的，可能以后会加吧😂
> 
> 780ex 应该也能刷，支持电信应该指的是支持电信上网，不是指的短信

大佬能给724那个增加一下合宙官方的推送吗

**Comment by 0wQ** [comment]
> > 可以用这个 https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html
> > 我卡都是有流量的，可能以后会加吧😂
> > 780ex 应该也能刷，支持电信应该指的是支持电信上网，不是指的短信
> 
> 大佬能给724那个增加一下合宙官方的推送吗

找到724无法访问合宙推送域名的原因了，这周加上

**Comment by heyzg** [comment]
> > > 可以用这个 https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html
> > > 我卡都是有流量的，可能以后会加吧😂
> > > 780ex 应该也能刷，支持电信应该指的是支持电信上网，不是指的短信
> > 
> > 
> > 大佬能给724那个增加一下合宙官方的推送吗
> 
> 找到724无法访问合宙推送域名的原因了，这几天加上

多谢大佬，我吃灰的724终于能用了，就差个724的WiFi了
