### ISSUE TITLE
网络消耗

### ISSUE THREAD

**Issue by remox** [0wQ/air780e-forwarder#19]
通知使用的网络是不是sim卡本身的流量？

**Comment by 0wQ** [comment]
是的

**Comment by remox** [comment]
我手上的卡没法使用流量，只能收发短信，有没有什么方案，比如文件之类的可以避开流量的方式来传输短信，只要能将内容传到服务器上就行。这方面的小白，感谢赐教～

**Comment by remox** [comment]
好的，非常感谢
