### ISSUE TITLE
待机几小时后程序卡死，能分析下问题在哪？

### ISSUE THREAD

**Issue by Robby-SS-Lu** [0wQ/air780e-forwarder#20]
虽然程序有添加了硬狗防止程序卡死，但是运行4个多小时后。还是无法转发信息。
Lua代码转发使用的是 Telegram。域名和地址不存在无法链接问题。

主要表现：
1、正常运行几个小时后，无法实现待机转发短信；
2、长按电源键无法调起流量查询。

能否给下思路，或者解决方法？

**Comment by 0wQ** [comment]
- 是否有在 `config.lua` 中开启 `LOW_POWER_MODE`
- [telegram-notify](https://github.com/0wQ/telegram-notify) 配置的域名能否正常访问
- 短按 POW 键能否发送测试通知
- 其他通知渠道是否正常

具体原因要看 Luatools 的日志，最好能插在电脑上打开 Luatools ，记录卡死时进行操作的日志
