### ISSUE TITLE
自己有需要就加了一个新功能，不知道提pr是否合适

### ISSUE THREAD

**Issue by goxofy** [0wQ/air780e-forwarder#21]
功能：当收到 MQTT,sms_content 样式的短信时，把sms_content转发到指定的mqtt服务器和topic上，其他设备可以订阅这个topic，来实现通过短信控制其他硬件设备的功能。

比如放在家里，家里ha智能家居系统订阅对应topic，即可通过短信控制家里的智能家居。属于是聊胜于无的功能。

**Comment by goxofy** [comment]
对了，没写过lua，照着文档照猫画虎写的，log也没加。。

**Comment by 0wQ** [comment]
本项目主要是短信转发，应该不会加入这个功能。
而且我感觉没必要通过发短信的方式转发 mqtt，开发板不能连接 wifi 都是 4G 公网，可以直接远程连接 mqtt 控制

**Comment by goxofy** [comment]
嗯明白，c3 那个 mqtt 我也搞了，就顺便把这个的也搞上了
