### ISSUE TITLE
添加香港卡支持？

### ISSUE THREAD

**Issue by Akityo** [0wQ/air780e-forwarder#22]
我尝试添加了45412，但是似乎不行

![image](https://github.com/0wQ/air780e-forwarder/assets/16974004/5a5e22a5-50df-437c-8f51-a020ce3834e0)

![image](https://github.com/0wQ/air780e-forwarder/assets/16974004/f8d03b06-da9e-4249-8c24-e2ce61c976be)

**Comment by 0wQ** [comment]
收到的通知内容是怎样的？

**Comment by Akityo** [comment]
不能推送消息，有看到消息队列，但是可能发不出去，没有网络

**Comment by 0wQ** [comment]
> 不能推送消息，有看到消息队列，但是可能发不出去，没有网络

刷个带rndis的固件，看看电脑能不能上网，或者插手机里能不能上网

**Comment by Akityo** [comment]
插手机可以，所以不知道是不是要设置什么，比如apn？ cmhk？
我刷了rndis的，下班回去试试

**Comment by Akityo** [comment]
我试了，rndis可以用，可以上网，感觉一切正常，但是就是信息发不了

我贴一下配置


![image](https://github.com/0wQ/air780e-forwarder/assets/16974004/b4e5dc1d-d112-4551-8738-a0f571fc0d51)


一开始我只加了钉钉，今天回来尝试添加了tg，也还是不行

**Comment by 0wQ** [comment]
telegram 需要配置一下自己的 TELEGRAM_PROXY_API，https://github.com/0wQ/telegram-notify

**Comment by Akityo** [comment]
噢噢，好的，但是钉钉的也不行，我一开始测试就只用的钉钉，以前在公司的电脑上是可以用的，国内的联通卡。。

**Comment by 0wQ** [comment]
插电脑能正常上网，应该设备发送通知也没问题啊

上电开机可以看这里，两个焊点短接就可以
![image](https://github.com/0wQ/air780e-forwarder/assets/20741439/40cf2cfb-b2ca-4169-851e-c4db04e082db)
https://cdn.openluat-luatcommunity.openluat.com/attachment/20221214113943532_%E5%BC%80%E5%8F%91%E6%9D%BFCore_Air780E%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8EV1.0.3.pdf

**Comment by Akityo** [comment]
怎么样可以在日志里面查看详细的信息，比如短信发送队列，打印到日志，lua不太懂

**Comment by 36h** [comment]
通过短信控制设备  请问这个要怎么实现？

**Comment by 0wQ** [comment]
> 通过短信控制设备 请问这个要怎么实现？

给开发板中的手机卡发一条短信, 短信内容格式: `SMS,10010,余额查询`, 开发板就会给 10010 发一条短信

**Comment by 0wQ** [comment]
看日志没有请求结果

> 怎么样可以在日志里面查看详细的信息，比如短信发送队列，打印到日志，lua不太懂

你好，试一下修改这里，看一下日志中 mobile.status() 值是多少
https://github.com/0wQ/air780e-forwarder/blob/e8b8a5a69300a8b7f846dff39d688735eebc8d2c/script/util_notify.lua#L415-L416
```lua
        log.info("mobile.status()", mobile.status())
        -- 消息队列非空, 且网络已注册
        if next(msg_queue) ~= nil then
```

**Comment by Akityo** [comment]
sorry，我的失误，为了防止被钉钉检测，改了一些关键词，导致关键词不匹配，发送失败

现在可以正常发通知了，但是好像没办法获取到手机号

**Comment by 0wQ** [comment]
> sorry，我的失误，为了防止被钉钉检测，改了一些关键词，导致关键词不匹配，发送失败
> 
> 现在可以正常发通知了，但是好像没办法获取到手机号

手机号是从 sim 卡读的，有些卡就是没有，貌似可以用安卓手机在手机设置中写进去，https://gitee.com/openLuat/LuatOS/issues/I6AB3N#note_17355962
