### ISSUE TITLE
邮箱转发配置以及改进

### ISSUE THREAD

**Issue by tomcat927** [0wQ/air780e-forwarder#24]
你好，我想问一下关于邮箱转发的配置。

看了一下， next-smtp-proxy这个项目和本项目的邮箱转发配置相关参数

我还是不太懂，该如何配置。

我又以下几个问题:
1）使用邮箱转发通道，是否就意味着需要，自己deploy一个 next-smtp-proxy服务，
然后根据对应参数配置？

————
感觉 next-smtp-proxy这种邮箱转发的配置不太友好，因为Vercel 分配的域名在中国大陆无法访问。
且使用方式个人感觉比较陌生，相关资料或者教程较少（反正您写的那个readme我也看不太懂，请见谅）

————

2）是否考虑添加以下这种邮箱转发方式:

借助stmp/pop登陆邮箱A，然后使用邮箱A发送短信内容到目标接收邮箱B

这种转发方式，直接通过代码即可实现，无需借助，某个类似 next-smtp-proxy这种服务，方式实现，个人感觉比较方便

————

说了怎么多，还是总结一下个:
能否出一个较详细的邮箱转发文档

或者采用我上面说的邮箱转发方式。

谢谢。

**Comment by 0wQ** [comment]
1. 是的，需要自己部署 next-smtp-proxy 这个项目，Vercel 可以自己绑定域名，修改一下域名 cname 就能访问了。或者可以使用Inotify 也支持推送到邮箱，再或者可以使用自定义 POST 请求对接一下其他支持邮箱的推送 API。
2. 之前有尝试过直接使用 smtp 协议发送，但能力有限，没写出来😂，所以临时写了 next-smtp-proxy 替代一下。

**Comment by tomcat927** [comment]
找平替产品吧。

**Comment by 0wQ** [comment]
[smtp分支](https://github.com/0wQ/air780e-forwarder/tree/smtp) 现在支持直接使用smtp协议发送邮件了，可以试一下

**Comment by tomcat927** [comment]
谢谢了，我fork的仓库已经用socket实现了该功能，目前加了远程更新和在配置文件的迁移。欢迎查看我的[readme](https://github.com/tomcat927/air724ug-forwarder/blob/main/README.md)上对项目的改进意见，


因为个人需求不同，后续我将闭源，做二次开发，谢谢。
