### ISSUE TITLE
DBG: diag com USB 断开连接 COM4 CommError,[WinError 22] 设备不识别此命令。

### ISSUE THREAD

**Issue by puexine** [0wQ/air780e-forwarder#3]

**Comment by 0wQ** [comment]
这一行删掉就可以了
https://github.com/0wQ/air780e-forwarder/blob/3f2d9652830cad85ae28f87e4ad4d6817c02eb31/script/main.lua#L118

**Comment by puexine** [comment]
> 这一行删掉就可以了
> 
> https://github.com/0wQ/air780e-forwarder/blob/3f2d9652830cad85ae28f87e4ad4d6817c02eb31/script/main.lua#L118

删掉了，但还是会出现
<img width="758" alt="Snipaste_2023-01-29_19-22-52" src="https://user-images.githubusercontent.com/743009/215322815-8490614d-4eb8-43cb-8d6d-f531d29900e5.png">

**Comment by 0wQ** [comment]
> > 这一行删掉就可以了
> > https://github.com/0wQ/air780e-forwarder/blob/3f2d9652830cad85ae28f87e4ad4d6817c02eb31/script/main.lua#L118
> 
> 删掉了，但还是会出现 <img alt="Snipaste_2023-01-29_19-22-52" width="758" src="https://user-images.githubusercontent.com/743009/215322815-8490614d-4eb8-43cb-8d6d-f531d29900e5.png">

应该不会这样，你把下面这几行都删掉，重新刷一下试试

https://github.com/0wQ/air780e-forwarder/blob/3f2d9652830cad85ae28f87e4ad4d6817c02eb31/script/main.lua#L116-L127

**Comment by puexine** [comment]
Lines 116 to 127删掉可以了

**Comment by 0wQ** [comment]
可以试一下 main 分支最新版本和 [LuatOS-SoC_V1103_EC618.soc](https://github.com/0wQ/air780e-forwarder/blob/main/LuatOS-SoC_V1103_EC618.soc) 固件, 默认是关闭低功耗模式

你也可以试着开启一下, 联网之后 20 秒会断开 USB 连接

https://github.com/0wQ/air780e-forwarder/blob/ddf0943049b35370a2bdb40891c0a780607b3864/script/config.lua#L46-L47
