### ISSUE TITLE
bark消息分组

### ISSUE THREAD

**Issue by opqrsting** [0wQ/air780e-forwarder#34]
-- bark 通知配置, https://github.com/Finb/Bark
    BARK_API = "https://api.day.app",
    BARK_KEY = "",

要给bark消息分组，
bark_apk需要怎么调整格式

**Comment by 0wQ** [comment]
可以尝试一下

https://github.com/0wQ/air780e-forwarder/blob/1a65311e1b41b251f298b5f0d1b62a643697ef53/script/util_notify.lua#L125-L125

 改为

```lua
local body = { body = msg, group = "group_name" }
```
