### ISSUE TITLE
Air780E不定时死机重启问题

### ISSUE THREAD

**Issue by zxq1998** [0wQ/air780e-forwarder#36]
使用的固件版本是：LuatOS-SoC_V1107_EC618
推送通知用的是：custom_post自定义的serverchan
其余的设置都是脚本默认的，有时候会一次性收到好多条开机通知，然后有的时候会经常看到自动重启，然后我就插在电脑上看日志，附件中是Luatools的显示，发现有时候会发生死机然后重启的情况，重启后会发生几十条的开机通知，然后又接着死机重启，来回循环，不知道是硬件问题还是软件问题，是否可以帮忙看下，如果还需要提供什么我可以提供。

[日志文件.txt](https://github.com/0wQ/air780e-forwarder/files/12852344/default.txt)

**Comment by 0wQ** [comment]
https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/config.lua#L3-L4

这里改成 `SLAVE` 试试呢

**Comment by zxq1998** [comment]
> https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/config.lua#L3-L4
> 
> 这里改成`SLAVE`尝试呢

改成`SLAVE`就没办法直接通过流量转发短信了吧

**Comment by 0wQ** [comment]
不会的，这指的是通过串口转发的配置，改成 `SLAVE` 应该可以临时解决，或者注释掉下面代码应该也可以解决

https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L63-L74

串口转发这部分应该是有bug，有时间修一下

**Comment by zxq1998** [comment]
好的，非常感谢，我这边按照你说的再测试下。

**Comment by zxq1998** [comment]
> 不会的，这指的是通过串口转发的配置，改成 `SLAVE` 应该可以临时解决，或者注释掉下面代码应该也可以解决
> 
> https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L63-L74
> 
> 串口转发这部分应该是有bug，有时间修一下

我这边开始只更改成`SLAVE`测试不行，还是会死机重启，后来我又按照你说的注释掉那段代码，然后从昨晚上到现在就没再死机重启了，短信转发也正常，不过看日志会一直出现下边的显示，还是很感谢作者能这么快回复。

[2023-10-10 20:06:34.405][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.407][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072!
[2023-10-10 20:06:34.408][000019253.354] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.576][000019253.611] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.578][000019253.612] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.607][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.611][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.612][000019253.643] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072!
[2023-10-10 20:06:34.613][000019253.644] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072!


[2023-10-10 14:36:56.954][000000065.374] I/user.uart read:	1	4	
[2023-10-10 14:36:56.977][000000065.377] I/user.uart read:	1	4	
[2023-10-10 14:36:56.979][000000065.379] I/user.uart read:	1	4	
[2023-10-10 14:36:56.981][000000065.381] I/user.uart read:	1	4	
[2023-10-10 14:36:56.983][000000065.384] I/user.uart read:	1	4	
[2023-10-10 14:36:56.984][000000065.386] I/user.uart read:	1	4	
[2023-10-10 14:36:56.986][000000065.389] I/user.uart read:	1	4	
[2023-10-10 14:36:56.988][000000065.391] I/user.uart read:	1	4

**Comment by 0wQ** [comment]
> > 不会的，这指的是通过串口转发的配置，改成 `SLAVE` 应该可以临时解决，或者注释掉下面代码应该也可以解决
> > https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L63-L74
> > 
> > 串口转发这部分应该是有bug，有时间修一下
> 
> 我这边开始只更改成`SLAVE`测试不行，还是会死机重启，后来我又按照你说的注释掉那段代码，然后从昨晚上到现在就没再死机重启了，短信转发也正常，不过看日志会一直出现下边的显示，还是很感谢作者能这么快回复。
> 
> [2023-10-10 20:06:34.405][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.407][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072! [2023-10-10 20:06:34.408][000019253.354] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.576][000019253.611] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.578][000019253.612] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.607][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.611][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.612][000019253.643] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.613][000019253.644] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072!
> 
> [2023-10-10 14:36:56.954][000000065.374] I/user.uart read: 1 4 [2023-10-10 14:36:56.977][000000065.377] I/user.uart read: 1 4 [2023-10-10 14:36:56.979][000000065.379] I/user.uart read: 1 4 [2023-10-10 14:36:56.981][000000065.381] I/user.uart read: 1 4 [2023-10-10 14:36:56.983][000000065.384] I/user.uart read: 1 4 [2023-10-10 14:36:56.984][000000065.386] I/user.uart read: 1 4 [2023-10-10 14:36:56.986][000000065.389] I/user.uart read: 1 4 [2023-10-10 14:36:56.988][000000065.391] I/user.uart read: 1 4

这里也删掉或者注释掉试试
https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L11-L12

**Comment by zxq1998** [comment]
> > > 不会的，这指的是通过串口转发的配置，改成 `SLAVE` 应该可以临时解决，或者注释掉下面代码应该也可以解决
> > > https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L63-L74
> > > 
> > > 串口转发这部分应该是有bug，有时间修一下
> > 
> > 
> > 我这边开始只更改成`SLAVE`测试不行，还是会死机重启，后来我又按照你说的注释掉那段代码，然后从昨晚上到现在就没再死机重启了，短信转发也正常，不过看日志会一直出现下边的显示，还是很感谢作者能这么快回复。
> > [2023-10-10 20:06:34.405][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.407][000019253.353] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072! [2023-10-10 20:06:34.408][000019253.354] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.576][000019253.611] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.578][000019253.612] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.607][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.611][000019253.642] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.612][000019253.643] prvUart_RxBufferAdd 398:uart1 rx 1,131072,131072! [2023-10-10 20:06:34.613][000019253.644] prvUart_RxBufferAdd 398:uart1 rx 2,131072,131072!
> > [2023-10-10 14:36:56.954][000000065.374] I/user.uart read: 1 4 [2023-10-10 14:36:56.977][000000065.377] I/user.uart read: 1 4 [2023-10-10 14:36:56.979][000000065.379] I/user.uart read: 1 4 [2023-10-10 14:36:56.981][000000065.381] I/user.uart read: 1 4 [2023-10-10 14:36:56.983][000000065.384] I/user.uart read: 1 4 [2023-10-10 14:36:56.984][000000065.386] I/user.uart read: 1 4 [2023-10-10 14:36:56.986][000000065.389] I/user.uart read: 1 4 [2023-10-10 14:36:56.988][000000065.391] I/user.uart read: 1 4
> 
> 这里也删掉或者注释掉试试
> 
> https://github.com/0wQ/air780e-forwarder/blob/cba87e9b6f30f76943e5c8fce8b242b4b4ef60e6/script/main.lua#L11-L12

这回测试就没有问题了，一切正常，感谢。
