### ISSUE TITLE
是否可以考虑增加pin码支持

### ISSUE THREAD

**Issue by xujiahai** [0wQ/air780e-forwarder#39]
是否可以在config.lua文件中增加pin码设置，可以自动解锁sim卡的pin码，谢谢

**Comment by iislong** [comment]
这得固件支持吧，曾经碰到过这问题，一直在找出错原因

**Comment by PandaTAT** [comment]
海外卡的话比如Vodafone可以先插在手机上关闭需要pin码的功能
