### ISSUE TITLE
air780E 遇到待机一晚，然后接收第一条短信要等待一分钟的情况。

### ISSUE THREAD

**Issue by pengnb** [0wQ/air780e-forwarder#46]
air780E 遇到待机一晚没接收短信，然后第二天接收第一条短信要等待一分钟的情况。能不能优化一下，加快短信接收。

**Comment by 0wQ** [comment]
更新最新代码，试试还有这个问题吗

**Comment by pengnb** [comment]
> 更新最新代码，试试还有这个问题吗

好的 我测试几天再回复。

**Comment by pengnb** [comment]
> 更新最新代码，试试还有这个问题吗

还是有问题，第二天接收第一条短信要等待一分钟

**Comment by 0wQ** [comment]
又更新了一下，应该可以解决😂 50adea2addab5c2d02632738c4ef169cd559ba84

**Comment by pengnb** [comment]
我再试试

**Comment by pengnb** [comment]
> 又更新了一下，应该可以解决😂 [50adea2](https://github.com/0wQ/air780e-forwarder/commit/50adea2addab5c2d02632738c4ef169cd559ba84)

还是很怪，收短信一时快一时慢。

**Comment by 0wQ** [comment]
是最新的代码吗？有没有开启低功耗模式

貌似一段时间没有网络请求的话，会出现能收到短信，但是需要重发10分钟左右才能发出去的情况。

之后又更新了一下，每30分钟发一次请求同步时间，然后每重发5次会开关飞行模式。

**Comment by pengnb** [comment]
> 是最新的代码吗？有没有开启低功耗模式
> 
> 貌似一段时间没有网络请求的话，会出现能收到短信，但是需要重发10分钟左右才能发出去的情况。
> 
> 之后又更新了一下，每30分钟发一次请求同步时间，然后每重发5次会开关飞行模式。

我是这个提交 （尝试修复短信延迟问题）的代码，我更新一下看看有没改善

**Comment by radiolee** [comment]
> 是最新的代码吗？有没有开启低功耗模式
> 
> 貌似一段时间没有网络请求的话，会出现能收到短信，但是需要重发10分钟左右才能发出去的情况。
> 
> 之后又更新了一下，每30分钟发一次请求同步时间，然后每重发5次会开关飞行模式。

没看到这个提问，也发现开启省电模式后，长时间待机，不论电话还是短信都要过5次重试才能发送。更蠢的是我看时间同步30分钟太频繁改为24小时了。。。 要不定时访问一个返回1字节的http或socket请求？

**Comment by radiolee** [comment]
关闭低功耗待机一晚，测试正常

**Comment by radiolee** [comment]
想短接powerkey旁的焊盘实现通电开机，把powerkey paddr更换为bootkey gpio0，处理完上下拉逻辑(与powerkey相反)后工作正常。最后开启低功耗模式按钮按下就没反应了，查了一下bootkey不是AGPIO，总算理解了大佬为什么用powerkey……

**Comment by radiolee** [comment]
连续开机62小时，最后一条转发推送5月1日下午15:46的情况下，5月2日下午14:55拨入电话，正常听到回铃声，推送延迟了一到两分钟，重试5次

**Comment by 0wQ** [comment]
> 连续开机62小时，最后一条转发推送5月1日下午15:46的情况下，5月2日下午14:55拨入电话，正常听到回铃声，推送延迟了一到两分钟，重试5次

30分钟间隔同步时间开了吗？

**Comment by radiolee** [comment]
> > 连续开机62小时，最后一条转发推送5月1日下午15:46的情况下，5月2日下午14:55拨入电话，正常听到回铃声，推送延迟了一到两分钟，重试5次
> 
> 30分钟间隔同步时间开了吗？

开了的。钉钉时间戳修复前一个版本，全默认值，bark推送，未打开省电模式

**Comment by radiolee** [comment]
今天分时段测试了一下，想知道几个小时无网络通讯会重发。最长间隔0503 1407pm～0504 0052，超过10小时都是秒推正常的。然后想起780E irtu之前做过一个报警器，115s一条心跳连onenet，长期测试发现每23-24小时会有一条重复连接在onenet上报1401错误，找了很久也没发现原因。

**Comment by radiolee** [comment]
0504 00:52～0504 23:10 重发5次(开机118小时)

**Comment by pengnb** [comment]
最新版本延迟体验很好

**Comment by radiolee** [comment]
0504 23:13~0505 08:59 秒推，间隔9小时46分（开机128小时）
0505 08:59~0505 21:32 重发5此，间隔12小时33分（开机140小时）
根据这几天测试，好像这个无法秒推需要重发时间间隔并不固定，从拨打电话到收到5次重发推送的时间间隔3分钟，绿色LED会狂闪。trace日志太大了也没法一直开着，使用没啥问题。

我的板加了几行cc相关的：每天定时用volte拨打一个电话，应该没啥影响。

**Comment by 0wQ** [comment]
@radiolee @pengnb 
可以更新一下，应该有改善。
添加了定时开关飞行模式，修改为重发2次开关飞行模式，删除了低功耗模式，并且发送失败后断电重启仍然可以重发

**Comment by pengnb** [comment]
> @radiolee @pengnb 可以更新一下，应该有改善。 添加了定时开关飞行模式，修改为重发2次开关飞行模式，删除了低功耗模式，并且发送失败后断电重启仍然可以重发

好

**Comment by radiolee** [comment]
> @radiolee @pengnb 可以更新一下，应该有改善。 添加了定时开关飞行模式，修改为重发2次开关飞行模式，删除了低功耗模式，并且发送失败后断电重启仍然可以重发

好的感谢

**Comment by pengnb** [comment]
> @radiolee @pengnb 可以更新一下，应该有改善。 添加了定时开关飞行模式，修改为重发2次开关飞行模式，删除了低功耗模式，并且发送失败后断电重启仍然可以重发

测试过了吗，我这边报错了 bark 转发，版本是（更新 README.md）
https://github.com/0wQ/air780e-forwarder/commit/61a2929d6dc40c384dcc65a5028129a11a3fd0be

util_notify_channel.lua:107: attempt to call a nil value (global 'urlencodeTab')
stack traceback:
	util_notify_channel.lua:107: in function 'util_notify_channel.bark'
	util_notify.lua:41: in upvalue 'send'
	util_notify.lua:115: in upvalue 'poll'
	util_notify.lua:160: in function <util_notify.lua:158>
[2024-05-06 23:06:36.743][000000007.170] E/main Luat: 
[2024-05-06 23:06:36.745][000000007.170] E/main util_notify_channel.lua:107: attempt to call a nil value (global 'urlencodeTab')
stack traceback:
	util_notify_channel.lua:107: in function 'util_notify_channel.bark'
	util_notify.lua:41: in upvalue 'send'
	util_notify.lua:115: in upvalue 'poll'
	util_notify.lua:160: in function <util_notify.lua:158>
[2024-05-06 23:06:36.748][000000007.171] E/main Lua VM exit!! reboot in 15000ms

**Comment by pengnb** [comment]
> @pengnb bark确实没测试，已经修复了 [45eb368](https://github.com/0wQ/air780e-forwarder/commit/45eb36838ec74bd011d9c638aa6a25a927c9780b)

没问题了

**Comment by radiolee** [comment]
抱歉昨晚有事没来得及测，今天上午已经看到更新，我也是用bark推的工作正常。

**Comment by pengnb** [comment]
最近折腾了一下air780E+w5500以太网模块，改了一下你的代码，数据走网线出去。发现短信延迟一分钟的日志如下:


![c3efa53e97eed525fdb9ad17ddd5cb2](https://github.com/0wQ/air780e-forwarder/assets/48441446/76800b4e-76eb-43f1-8eae-0736c9e8d1d9)
