### ISSUE TITLE
开机后没有主动同步系统时间导致钉钉加签验证失败

### ISSUE THREAD

**Issue by c90c90** [0wQ/air780e-forwarder#51]
建议在开机后主动同步一次时间，否则在时间未同步的情况下无法通过钉钉加签验证
`发送通知成功	code:	200	body:	{"errcode":310000,"errmsg":"description:机器人发送签名过期;solution:签名生成时间和发送时间请保持在 timestampms 以内;"}
`

**Comment by radiolee** [comment]
main.lua里在netready后面执行一次socket.sntp

**Comment by 0wQ** [comment]
已修复。应该是联通卡吧，部分联通卡好像不会从基站同步时间
