### ISSUE TITLE
是否可以考虑780epv增加拨打语音电话tts朗读短信功能？

### ISSUE THREAD

**Issue by radiolee** [0wQ/air780e-forwarder#52]
非实用功能，想学习一下。

通过cc demo成功可以成功拨打和接通电话了。但是tts demo要么是外置codec要么是内部管脚模拟(云喇叭)两个demo都是外放的，完全不懂如何在接通电话后把tts的语音送出去，例如短信内容或设备状态。

大佬能不能抽空研究一下，哪怕接通了只报个日期时间也行

**Comment by radiolee** [comment]
研究了一晚，tts功能很简单，资源放不下。要么外挂要么作罢

**Comment by 0wQ** [comment]
换724很简单可以实现，780epv官方也回复说做不了，https://gitee.com/openLuat/LuatOS/issues/I97L8X?from=project-issue

**Comment by radiolee** [comment]
> 换724很简单可以实现，780epv官方也回复说做不了，https://gitee.com/openLuat/LuatOS/issues/I97L8X?from=project-issue

感谢回复，我也是先搜到724的例子，然后再搜到718p的luatos api，尝试到今天凌晨1点多才放弃的。等空了扩一下spi flash再试

https://gitee.com/openLuat/luatos-soc-2023/attach_files
