### ISSUE TITLE
彩信没有办法转发，加一个彩信转发到的功能吗？

### ISSUE THREAD

**Issue by HKONE1** [0wQ/air780e-forwarder#58]
彩信没有办法正常转发，转发的彩信几乎都是同样的乱码，加一个彩信转发到的功能吗？还有表情符号，表情符号也只有部分能转发。
![Uploading 9919b7416a54de17e5ca02cf8b65c84.jpg…]()

**Comment by 0wQ** [comment]
上传的图片没有显示，合宙的固件应该是不支持彩信的
