### ISSUE TITLE
请问主从模式，一主对多从，从机通过串口转发消息，主机接受消息后转发到通知服务如何具体实现？

### ISSUE THREAD

**Issue by CrazyPeeta** [0wQ/air780e-forwarder#61]
首先感谢作者！这个项目简直太棒了。
我目前是有两张卡需要短信转发功能，一个是国内的移动卡，自带流量可以进行转发，另一个是国外的手机卡，流量按量计费，1M大概得1$，实在是用不起。
今天看本项目支持主从模式，一主对多从，从机通过串口转发消息，主机接受消息后转发到通知服务，这样的话，两个780E板，分别放我两张卡，海外的这张不消耗流量转送到移动卡上再发送，完美解决我的问题了

请问大佬，两块780E要怎么具体实现这个功能呢？
再次感谢分享

**Comment by 0wQ** [comment]
大概就是 从设备的 tx 引脚连接主设备的 rx 引脚，两块板子的 gnd 连接到一起

**Comment by CrazyPeeta** [comment]
> 大概就是 从设备的 tx 引脚连接主设备的 rx 引脚，两块板子的 gnd 连接到一起

感谢回复，这就试试

**Comment by CrazyPeeta** [comment]
大佬你好，项目测试一次就成功了！很好用，但是目前发现一个新的问题，多方搜索也没找到解决办法
我没有流量的从机备用卡，是香港的hahasim的卡，在手机里可以搜索信号正常收发短信，走的中国联通的信号，但是这个卡在780e模块中始终是提示正在注册中，过一会就变成注册被拒绝了，请问大佬有没有好的解决办法？

**Comment by CrazyPeeta** [comment]
> 大佬你好，项目测试一次就成功了！很好用，但是目前发现一个新的问题，多方搜索也没找到解决办法 我没有流量的从机备用卡，是香港的hahasim的卡，在手机里可以搜索信号正常收发短信，走的中国联通的信号，但是这个卡在780e模块中始终是提示正在注册中，过一会就变成注册被拒绝了，请问大佬有没有好的解决办法？

查看了已经关闭的issue,晚上尝试刷个带rndis的固件看看

**Comment by CrazyPeeta** [comment]
刷了不同固件 还是一样的无法注册，不知道是不是我的卡不支持
![06d31dd3-b7f1-41e5-91c0-8b41ff509ae2](https://github.com/user-attachments/assets/5b1f47d9-8f48-40bd-b514-98820734a15e)

**Comment by Feldan** [comment]
`air700`做从设备 `air780`做主设备

air700能正常串口发送数据

但是air780并不能转发数据出来。代码中加调试打印的话要在哪部分加啊
