### ISSUE TITLE
是否支持ipv6 http服务器

### ISSUE THREAD

**Issue by dbism** [0wQ/air780e-forwarder#62]

**Comment by 0wQ** [comment]
支持，需自行修改下面代码

https://github.com/0wQ/air780e-forwarder/blob/45eb36838ec74bd011d9c638aa6a25a927c9780b/script/main.lua#L25-L26

```lua
-- 开启 IPv6
mobile.ipv6(true)
```

https://github.com/0wQ/air780e-forwarder/blob/45eb36838ec74bd011d9c638aa6a25a927c9780b/script/util_http.lua#L31

```lua
local opts = { timeout = timeout, ipv6 = true }
```
