### ISSUE TITLE
有想过增加wxpusher支持吗

### ISSUE THREAD

**Issue by yiyindaren** [0wQ/air780e-forwarder#64]
我尝试过自己修改，用kimi助手写了一下lua脚本，但是缺少socket.http.lua、cjson啥的
下面是kimi的代码示例

local http = require("socket.http")
local ltn12 = require("ltn12")
local json = require("cjson")

-- 准备请求数据
local requestData = {
    appToken = "AT_xxx", -- 替换为你的appToken
    content = "<h1>H1标题</h1><br/><p style=\"color:red;\">欢迎你使用WxPusher，推荐使用HTML发送</p>",
    summary = "消息摘要",
    contentType = 2,
    topicIds = { 123 }, -- 替换为有效的topicIds
    uids = { "UID_xxxx" }, -- 替换为有效的uids
    url = "https://wxpusher.zjiecode.com",
    verifyPay = false,
    verifyPayType = 0
}

-- 转换为JSON格式
local jsonData = json.encode(requestData)

-- 设置请求头
local headers = {
    ["Content-Type"] = "application/json",
    ["User-Agent"] = "LuaSocket"
}

-- 发送POST请求
local response, statusCode = http.request{
    url = "https://wxpusher.zjiecode.com/api/send/message",
    method = "POST",
    headers = headers,
    source = ltn12.source.string(jsonData),
    sink = ltn12.sink.table(responseBody),
    protocol = "http"
}

-- 将响应数据转换为JSON
local responseJson = json.decode(table.concat(responseBody))

-- 打印响应
print("Status Code:", statusCode)
print("Response:", json.encode(responseJson, true))

**Comment by yiyindaren** [comment]
![1725884363682](https://github.com/user-attachments/assets/d8e45778-ce0b-4d04-ba7d-ee6132b44fc8)
上面好像markdown语法给代码整的识别有问题了

**Comment by 0wQ** [comment]
不用写代码，修改一下配置文件即可

1.
```lua
    NOTIFY_TYPE = "custom_post",
```

2.
https://github.com/0wQ/air780e-forwarder/blob/45eb36838ec74bd011d9c638aa6a25a927c9780b/script/config.lua#L10-L13

```lua
    -- custom_post 通知配置, 自定义 POST 请求, CUSTOM_POST_BODY_TABLE 中的 {msg} 会被替换为通知内容
    CUSTOM_POST_URL = "https://wxpusher.zjiecode.com/api/send/message/simple-push",
    CUSTOM_POST_CONTENT_TYPE = "application/json",
    CUSTOM_POST_BODY_TABLE = {
        ["content"] = "{msg}", -- 推送内容, 必传
        -- ["summary"] = "来自 Air780E 的短信", -- 消息摘要, 显示在微信聊天页面或者模版消息卡片上, 限制长度20(微信只能显示20), 可以不传, 不传默认截取 content 前面的内容
        ["contentType"] = 1, -- 内容类型, 2表示html, 推荐使用这种
        ["spt"] = "SPT_xx0", -- 发送SPT, 发送给单个用户时传 simplePushToken 即可
        -- ["sptList"] = { "SPT_xx1", "SPT_xx2" }, -- 发送SPT列表, 发送给多个用户时使用数组, 最多不能超过10个
    },
```

**Comment by yiyindaren** [comment]
感谢，我试试

**Comment by yiyindaren** [comment]
OK了，顺便把标准推送的也改了，感谢大佬！
