### ISSUE TITLE
sim有卡号信息设备无法读取本机号码

### ISSUE THREAD

**Issue by Yelp420** [0wQ/air780e-forwarder#65]
![1727949897131](https://github.com/user-attachments/assets/d4384f1e-4324-4c8d-a2b1-e7ab419a1b7c)
![1727950005497](https://github.com/user-attachments/assets/36a8e60b-94c7-4cf7-90ec-99eaee33bd1b)
![ffef2e421a270438ad0136647c4c833](https://github.com/user-attachments/assets/535b7434-24a4-4119-bd7d-0784935b6ece)

**Comment by 0wQ** [comment]
试试在手机上编辑一下改成别的号码，再看看模块能读出来吗

**Comment by Yelp420** [comment]
> 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗

![4228748aa626e628423901d19f43b95](https://github.com/user-attachments/assets/d38ca03d-50a0-427c-b41b-682df4ab7d75)
![1727950674846](https://github.com/user-attachments/assets/65821e5a-2ea5-43b7-bdfc-667c0b2eeb67)
![1727950735592](https://github.com/user-attachments/assets/441792b9-e32e-4c41-b008-a54a8066966b)

**Comment by Yelp420** [comment]
> 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗

已修改还是没法读取

**Comment by 0wQ** [comment]
> > 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗
> 
> 已修改还是没法读取

有 Air724 开发板吗，有的话可以通过 AT 指令来写入，780 貌似不支持

**Comment by Yelp420** [comment]
> > > 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗
> > 
> > 
> > 已修改还是没法读取
> 
> 有Air724开发板吗，有的话可以通过AT指令来写入，780三星不支持

目前没有可以购买 我用的小米修改的卡号信息

**Comment by 0wQ** [comment]
> > > > 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗
> > > 
> > > 
> > > 已修改还是没法读取
> > 
> > 
> > 有Air724开发板吗，有的话可以通过AT指令来写入，780三星不支持
> 
> 目前没有可以购买 我用的小米修改的卡号信息

没有测试过小米，本机号码有可能是存储在手机里的。我用 ColorOS 的手机测试是可以写入到 SIM 卡里的

**Comment by Yelp420** [comment]
> > > > > 尝试在手机上编辑一下改成其他号码，再看看模块能读出来吗
> > > > 
> > > > 
> > > > 已修改还是没法读取
> > > 
> > > 
> > > 有Air724开发板吗，有的话可以通过AT指令来写入，780三星不支持
> > 
> > 
> > 目前没有可以购买 我用的小米修改的卡号信息
> 
> 没有测试过小米，本机号码有可能是存储在手机里的。我用 ColorOS 的手机测试是可以写入到 SIM 卡里的

好的 我去找一部colorOS的手机测试一下 感谢解答

**Comment by Yelp420** [comment]
已解决

**Comment by Yelp420** [comment]
已解决 是卡未写入信息的原因 小米写不进去
