### ISSUE TITLE
问下这个设备是否可以支持？

### ISSUE THREAD

**Issue by kzh1980** [0wQ/air780e-forwarder#66]
https://www.domall.cn/Air780E-MiniCore.html#fromColId=2&_pp=2_471

之前的板子涨价了，买了这个AT版的，便宜是便宜，但感觉好像不能用。大佬得空帮忙判断下。

**Comment by 0wQ** [comment]
另外如果刷完灯不亮的话，`main.lua` 取消下面注释：
https://github.com/0wQ/air780e-forwarder/blob/45eb36838ec74bd011d9c638aa6a25a927c9780b/script/main.lua#L15-L16

```lua
-- 设置电平输出 3.3V 
pm.ioVol(pm.IOVOL_ALL_GPIO, 3300) 
```
