### ISSUE TITLE
怎么发送短信吖

### ISSUE THREAD

**Issue by mfblog** [0wQ/air780e-forwarder#69]
怎么发送短信吖

**Comment by 0wQ** [comment]
给设备发送以下格式的短信
```
SMS,18888888888,短信内容
```

**Comment by mfblog** [comment]
> 给设备发送以下格式的短信
> 
> ```
> SMS,18888888888,短信内容
> ```

😀我的意思从哪里发送，用Luatools发送吗

**Comment by 0wQ** [comment]
> > 给设备发送以下格式的短信
> > ```
> > SMS,18888888888,短信内容
> > ```
> 
> 😀我的意思从哪里发送，用Luatools发送吗

用手机给开发板上的卡号发上面格式的短信

**Comment by Droid-MAX** [comment]
我这边测试好像有点问题
