### ISSUE TITLE
可以支持多种推送并行吗？

### ISSUE THREAD

**Issue by lageev** [0wQ/air780e-forwarder#7]
看到config文件里推送类型只能填写一种 NOTIFY_TYPE = "xxx"

并且执行的时候走的是if else。

对lua语法和数据类型 不太了解，可不可以传一个数组进去，然后foreach一下

**Comment by 0wQ** [comment]
试试这个分支可以吗 https://github.com/0wQ/air780e-forwarder/tree/multi-channel-notify
